#!/bin/bash
serverHealthCheckInterval=0

while [ $serverHealthCheckInterval -lt 60 ];
do
	apacheProcessIds=$(pgrep apache2)

	if [ -z "$apacheProcessIds" ]
	then
		sudo apachectl graceful
	fi

	let serverHealthCheckInterval=serverHealthCheckInterval+1
	sleep 1
done
